version: '3.1'

services:
  regression-qa:
    image: python:3.10-slim
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "pytest --environment=qa tests/*"

  regression-dev:
    image: python:3.10-slim
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "pytest tests/*"

