version: '3.8'

services:
  regression-qa:
    image: python:3.10-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "pytest --environment=qa tests/* --disable-warnings --alluredir=allure-results-qa"

  regression-dev:
    image: python:3.10-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "pytest --environment=dev tests/* --disable-warnings --alluredir=allure-results-dev"

