name: Regression_DEV

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [prod, staging, test]  # Define multiple environments if needed

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python and Java
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Allure CLI
        run: |
          pip install allure-pytest
          sudo apt-get install allure

      - name: Run tests and generate Allure results
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: allure-report/${{ matrix.env }}  # Dynamic URL path
          clean: false
